### ISSUE TITLE
`///` is not handled correctly in atom 1.19 beta

### ISSUE THREAD

**Issue by fkjogu** [miqid/atom-language-rust#14] opened 2017-07-27 11:52 UTC
When using a triple slash `///`, the fold is set incorrectly. Try

```rust
/// Comment                 -| fold start
/// over                    -|
/// multiple                -|
/// lines                   -|
pub fn new() -> Foo {       -| fold end
    1 + 1;
    Foo {}
}
```

The actual function body is not inclued into the fold. This has other implications for other packages as well. See t9md/atom-vim-mode-plus/issues/819 for an example.

**Comment by miqid** [comment] 2017-07-27 13:59
@fkjogu, I skimmed through the issue you've linked but I don't have a clear idea about the problem you've raised. Alas, I'm not a regular `vim` user, so bear with me as I'm not terribly familiar with these selection key combinations mentioned.

So, I downloaded the `vim-mode-plus` package to try observe differences in behaviour between the grammars:

- Using the gutter down arrow to fold:
    - `//` or `///` comments collapse to the same result
    - `fn` definitions collapse to a different result (i.e. this package includes the end enclosing brace, which I believe is correct, the other doesn't)
- <kbd>v</kbd> <kbd>i</kbd> <kbd>f</kbd> on top of `fn` definitions, or inside them, selects the same result
- <kbd>v</kbd> <kbd>a</kbd> <kbd>f</kbd> on top of `fn` definitions, or inside them, selects a different result (i.e. once again, this package includes the end closing brace, the other doesn't)

After all that, I fail to see how this relates to the folding pattern you've suggested. Could you clarify the actual and expected behaviour in terms of usage?

**Comment by fkjogu** [comment] 2017-07-28 07:05
I do my best to clearify 😄. For me, using the snippet above, there is *no* fold for the function body in the gutter. Only for the comment, which also includes the line `pub fn...`. This is the actual issue, I'm having.

So I have:

```rust
v  | /// Comment                 -| fold start
   | /// over                    -|
   | /// multiple                -|
   | /// lines                   -|
   | pub fn new() -> Foo {       -| fold end
   |     1 + 1;
   |     Foo {}
   | }
```
Where `    | ` depicts the gutter and `v` a fold marker. I do *not* have a fold marker for the actual function body in this case. The relatiion to `vim-mode-plus` is, that it internally uses the same information that is provided by foldings.

Does this make things clearer?

**Comment by fkjogu** [comment] 2017-07-28 07:07
Whoops, I now understand the confusion. I was on `atom 1.19 beta`!

**Comment by miqid** [comment] 2017-07-28 14:53
Understood, thanks for elaborating.

I've checked out 1.19 beta and I can confirm reproducing the problem you've described. I couldn't find anything of interest from the beta release notes, but I'll review the documentation comment rules to see if something is interfering with block termination.

**Comment by miqid** [comment] 2017-07-30 14:32
@fkjogu, I've made some changes that address this problem in the next release ([0.12.2](https://github.com/miqid/atom-language-rust/releases/tag/v0.12.2)).

I wasn't comfortable with making any changes at all initially since this is targeting a beta version of Atom, but there were some corrections I needed to make around match rules for documentation blocks anyway.

So, do update this package and feel free to re-open the issue if you're still having problems with the folding behaviour.

**Closed by miqid** 2017-07-30 14:32 UTC
Labels: bug
